<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net8.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MyDmsVn.Server.Application\MyDmsVn.Server.Application.csproj" />
    <ProjectReference Include="..\MyDmsVn.Server.Domain\MyDmsVn.Server.Domain.csproj" />
  </ItemGroup>
</Project>
